### ISSUE TITLE
Widescreen issue / bug

### ISSUE THREAD

**Issue by niunisas** [iTexZoz/RageUI#107]
Hi,

While testing RageUI noticed that there's an issue for widescreens. Menu UI is in the right place, but functionality for it end up in the wrong spot this causes Sliders, Grids, Color pallets, Opacity menus unresponsive or in other words, you can control it if you know the spot. Posting screenshot below, current resolution is: 2560x1080 marked in red boxes where controls end up.
![unknown](https://user-images.githubusercontent.com/55489629/94683118-a960bb80-032e-11eb-82b5-8d79593226d2.png)

Maybe there's an easy fix for that? On 1080p it seems to work fine.

**Comment by iTexZoz** [comment]
Hello, I don't have a screen of this size,

it would be never to be solved

**Comment by niunisas** [comment]
I guess you can't use same values as drawing? Because it's drawn in correct place.

**Comment by niunisas** [comment]
After more testing, it looks like drawing uses safezone, but controls not. Because if I do mainMenu.Safezone = false, it works great on widescreen, but alligned on top left corner.
