### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by jadou7** [iTexZoz/RageUI#119]
Hello,

Is there the possibility to create a cooldown on a button? If yes, how ?

**Comment by Decodaz** [comment]
Just set an Timeout in the onSelected = function()

`        RageUI.IsVisible(dumbmenu, function()
                RageUI.Button(" ", " ", {}, not cooldown, {
                    onSelected = function()
                        cooldown = true

                        Citizen.SetTimeout(2500, function()
                            cooldown = false
                        end)

                    end})
            end
        end)
    end
end)`

I did it like this, may be not the best way idk
