### ISSUE TITLE
badge doesn't show

### ISSUE THREAD

**Issue by Nimplex** [iTexZoz/RageUI#121]
Hello, i wanted to add badge to button, but it don't works.

My code:
```lua
            RageUI.Button('Dodaj bronie', '', { RightBadge = RageUI.BadgeStyle.Car }, true, {
                onSelected = function()
                    TriggerEvent('4menu:addWeapons')
                end
            })
```
Screenshot:
![image](https://user-images.githubusercontent.com/39964594/111077625-f528ab00-84f1-11eb-9b7b-1de2a73baa2c.png)

**Comment by norfair00** [comment]
Same error

**Comment by Nimplex** [comment]
Why did you closed issue?
