### ISSUE TITLE
My list does not change

### ISSUE THREAD

**Issue by FeniixDev** [iTexZoz/RageUI#124]
[EN]
Hello,

I am using RageUI V2 but when I display a list it works but I see only one element (the index), I cannot change yet the action is detected.

Can you help me ?
Thanks

[FR]
Salut,

J'utilise RageUI V2 mais lorsque j'affiche une liste ça fonctionne mais je vois qu'un seul élément (l'index), je ne peux pas changer pourtant l'action est bien détecté..

Pouvez vous m'aider ?
Merci

![image](https://user-images.githubusercontent.com/18040403/115324420-2435da80-a18a-11eb-813b-deb713234a2f.png)
![image](https://user-images.githubusercontent.com/18040403/115324471-3879d780-a18a-11eb-867d-d4b962b4d121.png)

**Comment by FeaReDGlock** [comment]
[EN]
Look the exemple.lua, you have a list that work.

[FR]
Regarde dans RageUI tu as un fichier exemple.lua avec une liste que tu peux utiliser, qui fonctionne.

**Comment by FeniixDev** [comment]
Merci pour ta réponse mais justement j’ai bien repris cet exemple (j’ai juste modifié les éléments) et ça ne fonctionne pas :/

**Comment by FeaReDGlock** [comment]
Alors oui c'est assez compliqué car en faite la Value c'est 1 puis 2 puis 3 puis 4 par exemple.
En gros tu peux avoir écrit dedans ton : mp_m_freemode_01 Cela ne changera pas.

Je vais te montrer un bout d'exemple de mon code avec la version List

`

local veh = {
    "Blista",
    "Oracle",
    "Baller4",
    "Raiden"
}

RageUI.List('Liste de voiture', {
                { Name = "Blista", Value = 1 },
                { Name = "Oracle", Value = 2 },
                { Name = "Baller", Value = 3 },
                { Name = "Raiden", Value = 4 },
            }, index.list, description, {}, true, {
                onListChange = function(Index, Item)
                    index.list = Index;
                end,
                
                onSelected = function(Index, Item)
                    local model = GetHashKey(veh[Index])
                    RequestModel(model)
                    while not HasModelLoaded(model) do Citizen.Wait(10) end
                    local pos = GetEntityCoords(PlayerPedId())
                    local vehicle = CreateVehicle(model, pos.x-3, pos.y, pos.z, 90, true, false)
                end,
            })
`

Il faut que tu créer un array en haut pour après pouvoir le réutiliser sur ton script.
Si tu sais bien lire comme il faut tu vas vite comprendre mon script pour que tu puisse comprendre pourquoi le tien ne marche pas.

**Comment by iTexZoz** [comment]
English only.
