### ISSUE TITLE
Live update with RageUI

### ISSUE THREAD

**Issue by Rubylium** [iTexZoz/RageUI#27]
Not an issue but an question about RageUI.
Will using NativeUI reloaded or not, i always got the issue of live updating an var. For exemple an menu title displaying the var test = 2. Will the menu if open if i change the var test to 3 the menu will still display 2 until i close it and open it again. Do RageUI allow live updating ? ( Not sure how to say it, pretty sure live update is not the correct thing to describe this ^^' )

**Comment by Parow** [comment]
Yes it does
