### ISSUE TITLE
Weird double action ( FR ISSUE )

### ISSUE THREAD

**Issue by Rubylium** [iTexZoz/RageUI#32]
Certaine action son comptabilisé deux fois, j'ai remarquer le problème sur les mouvement haut / bas et entré des menu, aucun problème sur les slider ou list.
Par exemple sur certain menu quand on appuie sur entré il va nous comptabilisé deux fois entré, de même quand on circule dans les différente options d'un menu avec les flèche au et bas, assez embêtant dans des shops ^^

**Comment by iTexZoz** [comment]
English only please. no french support here.
