### ISSUE TITLE
Usage mémoire et CPU

### ISSUE THREAD

**Issue by Slyker** [iTexZoz/RageUI#33]
Salut je voulais savoir si le menu était déchargé quand il est pas ouvert ? parce que la consommation de mémoire reste stable même après la fermeture du menu, je fais peut-être mal quelque chose maybe si quelqu’un a des pistes..
Pour la conso CPU c'est sans doute lié à mon script c'est possible
![image](https://user-images.githubusercontent.com/12174146/72297023-483b6f80-365b-11ea-8a60-00daef88e2dc.png)
![image](https://user-images.githubusercontent.com/12174146/72297217-bb44e600-365b-11ea-9fc3-7a7c847dd7cf.png)

**Comment by Slyker** [comment]
De plus quand j'y penses, quand je ferme mon menu il se réouvre sur l'élément qui était actif quand j'ai fermé

**Comment by nowherem** [comment]
Salut, je pense que ça viens de ton script car voici le miens. ouvert/fermer
<img width="391" alt="open" src="https://user-images.githubusercontent.com/35810818/72368686-d9175700-36fe-11ea-8a8b-6a6288da92b3.png">
<img width="391" alt="close" src="https://user-images.githubusercontent.com/35810818/72368710-e2082880-36fe-11ea-8ea6-f48c3da5e5b4.png">

**Comment by Slyker** [comment]
Ah au moins je sais maintenant, il y a beaucoup d'élement dans ton menu ? Le miens est généré via du code

**Comment by nowherem** [comment]
J'ai 10 menu actuellement, complet exemple (clostheshop, barbershop, tattoo, fuel etc..) tout est dans un même dossier au passage. mais de ce que j'ai pu voir sur ton screen, c'est que tu dois avoir un boucle qui recherche quelque chose tout le temps, pour monter à 95MIB

**Comment by Slyker** [comment]
Oui certains des menus sont générés en fonction d'une table, tu pense que c'est possible de charger la table une fois au chargement ? J'utilise la methode RMenu si ça peut t'aider.
Sachant que je suis monté bien plus haut en laissant tourner le scritpt
Quasiment 1GB de mémoire.

**Comment by Slyker** [comment]
Sinon a voir si c'est possible de complètement delete le menu quand je n'en ai pas besoin et de le reprendre quand il faut

**Comment by Slyker** [comment]
Désolé pour la perte de temps je viens de voir que j'avais une boucle addsubmenu dans dans un CreateWhile... Merci à toi @nowherem maintenant je connais les limites ;)
