### ISSUE TITLE
Problème avec les color panel ?

### ISSUE THREAD

**Issue by Slyker** [iTexZoz/RageUI#34]
Salut j'ai un soucis avec les colour panel le barre qui nous indique où on est ne revient pas au début comme on peut le voir sur le screen
Quelqu'un à reussi à le faire fonctionner ?

![image](https://user-images.githubusercontent.com/12174146/72636377-37427500-395f-11ea-9c83-0528ce1cad9d.png)

**Comment by Slyker** [comment]
Et aussi je me demandais si c'était possible d'ouvrir un submenu depuis un instructional button ?

**Comment by MRVGithub** [comment]
Salut ! J'avais le même problème mais je l'ai vite réglé en regardant cette example : https://github.com/iTexZoz/RageUI/blob/5ef070993526b5a8d3945efe543eb018c1f116e6/example.lua tu devrais y arriver avec ça.

**Comment by Slyker** [comment]
T'es au top merci @MRVGithub et pour ouvrir un sub menu depuis un instructional button il y a des pistes dans ce fichier ?

**Comment by MRVGithub** [comment]
Pas de soucis :), et non, il faut juste draw l'instructional buttons et si il est draw alors tu vérifies si le joueur appuie sur les touches voulues pour ensuite effectuer l'action souhaitée.

**Comment by Slyker** [comment]
Oui jusque là j'ai réussi mais quand j'essaye d'ouvrir mon deuxième menu ça fait tout sauter ( à noter que pour mes test le deuxième menu est celui qui est en exemple )

**Comment by nowherem** [comment]
Salut, montre ton code?

**Comment by iTexZoz** [comment]
English only please. no french support here.
