### ISSUE TITLE
Menu not correctly reset

### ISSUE THREAD

**Issue by Rubylium** [iTexZoz/RageUI#52]
Opening a menu while another menu from the same RMenu is open will not completely close the already opened menu. And when you open back the menu, the menu will be opened 2 times.

Repo: 
I open my menu ``RageUI.Visible(RMenu:Get('core', 'main'), not RageUI.Visible(RMenu:Get('core', 'main')))`` 
Then without closing it i open my menu ``RageUI.Visible(RMenu:Get('core', 'mecano_main'), not RageUI.Visible(RMenu:Get('core', 'mecano_main')))``

The first menu "core main" will be closed and the "core mecano_main" will be displayed nicely, but now if i close the mecano_main and i open back core main, the menu will be displayed 2 times. I supposed this is due to the menu not being closed but just not displayed.

Screenshot when the menu is openned 2 times:
![image](https://user-images.githubusercontent.com/19718604/82142822-77e3c980-983f-11ea-81e6-ceef90bf72ba.png)
Also when the menu is openned 2 times ( Or more ), if you close it you get this error:
![image](https://user-images.githubusercontent.com/19718604/82142828-892cd600-983f-11ea-9d7d-f20ed83cf990.png)

Hope this can help :)

**Comment by Rubylium** [comment]
Bump ? Any news / tips ?

**Comment by Naytoxp** [comment]
Maybe you can try to check if any menu is already open, and if it is, RageUI.CloseAll(), maybe not the proper way, but it may solve your issue

**Comment by Rubylium** [comment]
Already tried, not working at all.

**Comment by ScouseMouse21** [comment]
Am having an issue very much like this too here is a video of it to maybe give you a better understanding ( https://streamable.com/xduamc )

I open up the first menu, I select a vehicle and after I spawn that vehicle and attempt to open another menu ( My Interaction Menu M KEY ) It opens the dealership menu back up too. Now it will keep doing this until I hit BACKSPACE when it is open once that happens everything goes back to normal and then I get the same error 
![ERROR2](https://user-images.githubusercontent.com/40149867/82851044-68771700-9ef6-11ea-9167-e89d5b9dd304.png)

Hope this can help you guys out :)
-ScouseMouse

**Comment by Rubylium** [comment]
issue still present
Repro again:
Run the code in this order

Open you'r menu
`RageUI.Visible(RMenu:Get('core', 'main'), not RageUI.Visible(RMenu:Get('core', 'main')))`

This will close the menu
`RageUI.Visible(RMenu:Get('core', 'main'), not RageUI.Visible(RMenu:Get('core', 'main')))`

This will open the menu, but this time the menu will be opened 2 time like if the last menu was not correctly closed
`RageUI.Visible(RMenu:Get('core', 'main'), not RageUI.Visible(RMenu:Get('core', 'main')))`
