### ISSUE TITLE
[ERROR] UIButton attempted to call a boolean value. 

### ISSUE THREAD

**Issue by ScouseMouse21** [iTexZoz/RageUI#55]
I recently updated RageUI and having an issue when it comes to creating buttons. They used to work back on the old version I had but after updating today it sorta broke. I went ahead and copied/pasted the RageUI.Button from the example Lua menu and still running into the same issue. Upon removing these lines of code: 
```
RageUI.Button("Cook !", "Cook the dish with the appropriate ingredients and ketchup.", {RightBadge = RageUI.BadgeStyle.Tick }, true, function(Hovered, Active, Selected)
      if (Selected) then
      end
end)
```
It works as intended

Here is the error am currently having 
![ERROR](https://user-images.githubusercontent.com/40149867/82846570-69ea1480-9ee1-11ea-88ed-8f6508a97822.png)

Here is the current RageUI.CreateWhile loop I have 
```
RageUI.CreateWhile(1.0, true, function()

    RageUI.IsVisible(RMenu:Get('CharacterCreationMenu', 'main'), true, true, true, function()
        --- Items
        RageUI.Separator("Center Text")

        RageUI.Button("Cook !", "Cook the dish with the appropriate ingredients and ketchup.", { RightBadge = RageUI.BadgeStyle.Tick }, true, function(Hovered, Active, Selected)
            if (Selected) then

            end
        end)

    end, function()

    end)
end)
```

**Thank you**
ScouseMouse.

**Comment by Naytoxp** [comment]
Hey, RageUI.Button has been updated, now there is RageUI.Button without Style Param, and RageUI.ButtonWithStyle with Style Param, look to src/client/items/UIButton.lua for the params

**Comment by ScouseMouse21** [comment]
Hey, I feel stupid thank you very much
