### ISSUE TITLE
Double Action slide menu

### ISSUE THREAD

**Issue by Bentozoox** [iTexZoz/RageUI#56]
Hello I have a little problem. When I'm in the slide, there is sometimes a double action. When I press the right or left arrow, a category is sometimes passed. This problem was explained by a person whose ticket was closed, so I don't know the solution. thank you

**Comment by SirAlexJz** [comment]
I was experiencing a similar issue with the List item. Pressing the left/right arrow key will sometimes skip over an index or two and to be honest up and down just generally will sometimes do this.

I had a look in MenuController.lua and I suspect its is to do with the "interesting" way in which controls are triggered. Using time to determine whether something is active or not is simply just asking for trouble.

**This next part is directed at a maintainer**
A suggestion for a method that should fix this is by removing the dependency on timings to determine whether a key "should" be active or not. 
I can see that by the way this library is written that it's not a small job, I appreciate that, but needs considering as this has put me off, and surely other people as well, from using this.

**Comment by iTexZoz** [comment]
Good morning,

Can you share the part of your code that causes the problem, so I can reproduce the problem you encountered.

However, this problem is often caused by loading an animation dictionary or model.

Waiting for your answer to help you solve this problem.

**Comment by SirAlexJz** [comment]
> **This next part is directed at a maintainer**
> A suggestion for a method that should fix this is by removing the dependency on timings to determine whether a key "should" be active or not.
> I can see that by the way this library is written that it's not a small job, I appreciate that, but needs considering as this has put me off, and surely other people as well, from using this.
