### ISSUE TITLE
Seems to have an hided "up" button

### ISSUE THREAD

**Issue by LH-Lawliet** [iTexZoz/RageUI#59]
With the 3 GridPanel there is like an hided button like:
![image](https://user-images.githubusercontent.com/35814039/85159256-8d447d00-b25d-11ea-8828-3eb06c602983.png)

**Comment by Bentozoox** [comment]
Hello I have the same issue :( I think that this...
![image](https://user-images.githubusercontent.com/65660007/87347126-fc5a7c00-c552-11ea-803a-de9ff113532c.png)
 Solved?

**Comment by iTexZoz** [comment]
Hello,

I know about this little problem, it will be solved in the next major update of RageUI available on the experimental branch. 

👍

**Comment by iTexZoz** [comment]
Issue is fixed on experimental branch.
