### ISSUE TITLE
Glare is not in the right position

### ISSUE THREAD

**Issue by arthur-rl** [iTexZoz/RageUI#62]
When changing the position of the menu, the glare seems to hang off the side!
![img](https://i.arthurl.me/ygmlehpv.png)
here is the code for making the menu if it helps
```lua
RMenu.Add('cmgeventmenu', 'main', RageUI.CreateMenu("CMG Events", "CMG Event Manager", 1400,100))
```

**Comment by iTexZoz** [comment]
Solved on experimental branch 👍
