### ISSUE TITLE
Mouse interaction with menus is inconsistent/incorrect

### ISSUE THREAD

**Issue by PainedPsyche** [iTexZoz/RageUI#89]
When trying to interact with a menu or submenu using mouse, the behavior is weird and inconsistent, sometimes it only highlights the clicked item, sometimes it does nothing, sometimes it interacts with an item one index earlier as if the actual position was off, sometimes interacts correctly.

The item list's "<" and ">" arrows are not interactive at all (not sure if intended).

**Comment by Naytoxp** [comment]
Hey, i can only answer you for the List issue, i think it is intended, because if you look at the source code, it is only "characters" and are just part of the style, i don't think it is possible to make it working, for the other things i can tell you because i don't use the mouse very much
