### ISSUE TITLE
Grid associated with a list that changes it's positions does not update

### ISSUE THREAD

**Issue by PainedPsyche** [iTexZoz/RageUI#96]
It seems like feedback to the grid is only possible by actually interacting with the grid itself and if something else updates it's positions, the updates are not displayed.

Updating grids by 'outside' means is needed to implement facial feature "presets" that GTA Online character creator uses.

Example code that should demonstrate this issue:

```
Presets = {
  One = {
    Names = { 'First', 'Second', 'Third' },
    Values = {
      [1] = { x = 0.5, y = 0.5 },
      [2] = { x = 0.1, y = 1.0 },
      [3] = { x = 1.0, y = 0.4 },
    }
  }
}

DataSet = {
  x = 0.0,
  y = 0.0
}

menu.Items = function()
  RageUI.Item.List('List Name', Presets.One.Names, 1, nil, {}, true, {
    onListChange = function(index, items)
      DataSet.x = Presets.One.Values[index].x
      DataSet.y = Presets.One.Values[index].y
    end,
  })
end

menu.Panels = function()
  RageUI.Panel.Grid(DataSet.x, DataSet.y, 'Top', 'Bottom', 'Left', 'Right', {
    onPositionChange = function(x, y)
    end,
    onSelected = function(x, y)
    end
  }, 1)
end
```

**Comment by Mr-Craig** [comment]
The first two variables in ```RageUI.Panel.Grid``` are only used to generate the initial value of the grid. They aren't linked.
