### ISSUE TITLE
Documentation website unavailable

### ISSUE THREAD

**Issue by Dylan-Duault** [iTexZoz/RageUI#99]
Hi,

Thank you for this amazing resource, everything is in the title:
https://rageui.dylan-malandain.io/ is not working.

Thanks,
Dylan

**Comment by xen0risDEV** [comment]
Hi Dylan, the documentation was delete by iTexZoz.

**Comment by iTexZoz** [comment]
Hello, I invite you to read the message present on my discord.

Here is a small part of this message

```
All this is solved, however no documentation will be provided because I have other things to do, anyway nobody understands my documentation :), a lot of things are explained in the example menu, so this one will do.
```

**Comment by Dylan-Duault** [comment]
Alright, that makes the project not really easy to use but I understand the reasons behind your choice, we will read your code to understand how to use RageUI.

I created a pull request #100 to remove the documentation link from the readme file.
